version: '3'
services:
  web:
    image: nginx:latest 
    container_name: web
    ports:
     - "80:80"
    volumes:
     - "./client/nginx.conf:/etc/nginx/conf.d/default.conf"
     - "./client/tmp:/usr/share/nginx/html"

    command: /bin/bash -c "nginx -g 'daemon off;'"

    networks:
      nn:
        ipv4_address: 192.168.5.101

  django:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
    volumes:
      - ./server:/home/app
      - ./server/db:/home/app/db/

    networks: 
      nn:
        ipv4_address: 192.168.5.102

networks: ##定义网络组
  nn: ## 网络组名称
    driver: bridge ## 网络的模式
    ipam: ## 配置网络
      driver: default
      config:
        - subnet: 192.168.5.0/24