# Generated by Django 2.1 on 2019-06-02 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signal',
            old_name='is_recieved',
            new_name='is_received',
        ),
    ]
